### ISSUE TITLE
Does not currently work with AutoCAD 2018

### ISSUE THREAD

**Issue by cxp6696** [cyrillef/OPMNetExt#3]
Hi Cyrillef,

I know this implementation is not including AutoCAD 2018, but do you have an implementation for that by any chance? I attempted to run your implementation on 2018 and it didn't work out of the box. I was getting "could not load assembly" errors when I'm trying to make the call out to get the PropertyManager at 

IPropertyManager2 pPropMan =
(IPropertyManager2)xOPM.xGET_OPMPROPERTY_MANAGER(lineDesc);

If not, could you offer me some guidance on what all it took to get it ported? I'm a C# developer by trade so my C++ is spotty at best.

Thank you in advance,

Clarence

**Comment by cyrillef** [comment]
Hi, we will take a look asap

**Comment by cyrillef** [comment]
We migrated the plugin to 2018, pull the changes
