### ISSUE TITLE
IUnknown usage

### ISSUE THREAD

**Issue by ligazetom** [cyrillef/OPMNetExt#6]
I hate doing this (sorry, not really an issue), but I don't really want to @ you on twitter and there is nothing anywhere on this topic. I'm struggling for a few days with something that should be pretty obvious but to me is not.

How on earth do you get handle or object id from the pUnk in IDynamicProperty2 methods?

What you are getting is ptr to IUknown, disguised as System.__COMObject handle. What should I cast it to to make it work?

Once again, sorry I'm just desperate here.

**Comment by ligazetom** [comment]
Couldn't make it work with IDynamicProperty2, but I reimplemented IDynamicProperty, where I get objectID right away. Still not sure how to use the second approach :) Thank you.

**Comment by OWiger** [comment]
> Couldn't make it work with IDynamicProperty2, but I reimplemented IDynamicProperty, where I get objectID right away. Still not sure how to use the second approach :) Thank you.

var objId = DBObject.FromAcadObject(pUnk);

**Comment by Janson-Lau** [comment]
How to categorizedProperty in our OPM?
